config/routes.rb
Rails.application.routes.draw do

  root 'recipes#index'

  resources :recipes, :labels

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

   # These routes will be for signup. The first renders a form in the browser, the second will
   # receive the form and create a user in our database using the data given to us by the user.
   # get '/signup' => 'users#new'
   # post '/users' => 'users#create'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings
  has_many :recipes, through: :labelings

  def to_s
  	description
  end
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :recipe
  belongs_to :label
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  validates :title, :body, presence: true

  has_many :labelings, :dependent => :delete_all
  has_many :labels, through: :labelings

  def label_list
  	labels.join(", ")
  end

  def label_list=(labels_string)
  	label_descriptions = labels_string.split(",").collect{|s| s.strip.downcase}.uniq
  	new_or_found_labels = label_descriptions.collect { |description| Label.find_or_create_by(description: description) }
  	self.labels = new_or_found_labels
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_filter :authorize

  def index
    @labels = Label.all
  end

  def show
    @label = Label.find(params[:id])
  end

  def new
    # very simple code to create an empty post and send the user
    # to the New view for it (new.html.erb), which will have a
    # form for creating the post
  end

  def create
    # code to create a new post based on the parameters that
    # were submitted with the form (and are now available in the
    # params hash)
  end

  def edit
    # very simple code to find the post we want and send the
    # user to the Edit view for it(edit.html.erb), which has a
    # form for editing the post
  end

  def update
    # code to figure out which post we're trying to update, then
    # actually update the attributes of that post.  Once that's
    # done, redirect us to somewhere like the Show page for that
    # post
  end

  def destroy
    flash.now[:notice] = "Delete operation failed" unless Label.destroy(params[:id])
    redirect_to :action => :index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authorize

  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true).paginate(page: params[:page], per_page: 5)
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    @labels = @recipe.labels
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(whitelisted_recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      flash.now[:error] = "Recipe not created"
      render :new
    end
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
  end

  def update
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.assign_attributes(whitelisted_recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      @errors = @recipe.errors.full_messages
    end
  end

  def destroy
    flash.now[:notice] = "Delete operation failed" unless Recipe.destroy(params[:id])
    redirect_to :action => :index
  end

  def whitelisted_recipe_params
    params.require(:recipe).permit(:title, :body, :label_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    session[:user_id] != nil
  end

  def current_user
    if logged_in?
      User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/labels/index.html.erb
<h2>All Labels</h2>

<ul id="labels">
  <% @labels.each do |label| %>
    <li>
      <%= link_to label.description, label_path(label) %>


    </li><br>
  <% end %>
</ul>

app/views/labels/show.html.erb
<h2>Recipes Labelled as <%= @label.description %></h2>

<ul>
  <% @label.recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe_path(recipe) %></li><br>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><a href="/">Home</a></li>&nbsp;&nbsp;
          <% if logged_in? %>
            <li><%= link_to "Add a Recipe", new_recipe_path %></li>&nbsp;&nbsp;
            <li><%= link_to "All Labels", labels_path %></li>&nbsp;&nbsp;
            <%= link_to "Logout", '/logout' %>
          <% else %>
            <li><%= link_to 'Login', '/login' %></li>
          <% end %>
      </ul>
    </nav>
    <div class="container">
      <%= yield %>
     </div>
  </body>
</html>

app/views/recipes/_new_form.html.erb
<div class="error">
  <% if @recipe.errors.any? %>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<%= form_for @recipe do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, size: "60x12" %>
  </p>
  <p>
    <%= f.label :label_list %><br>
    <%= f.text_field :label_list %>
  </p>
    <%= f.submit "Create" %>
<% end %>

app/views/recipes/edit.html.erb
<div class="error">
  <% if @recipe.errors.any? %>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<%= form_for @recipe do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, size: "60x12" %>
  </p>
    <%= f.submit "Save changes" %>
<% end %>

app/views/recipes/index.html.erb
<h1>All the recipes!</h1>

<div class="search-area">

	<%= search_form_for @q do |f| %>

	  <%= f.label :title_cont %>
	  <%= f.search_field :title_cont %>

	  <%= f.label :body_cont %>
	  <%= f.search_field :body_cont %>

	  <%= f.label :title_or_body_cont %>
	  <%= f.search_field :title_or_body_cont %>

	  <%= f.submit %><br><br>
	<% end %>
</div>

<% @recipes.each do |recipe| %>
  <b><%= link_to recipe.title, recipe_path(recipe) %></b><br>
  <%= recipe.body %><br><br>
<% end %>

<%= will_paginate @recipes %>

app/views/recipes/new.html.erb
<h2>Add a Recipe</h2>

<%= render partial: 'new_form' %>

app/views/recipes/show.html.erb
<b><%= @recipe.title %><br></b>
<%= @recipe.body %><br>

<p>
  Labels:
  <% @recipe.labels.each do |label| %>
  <ul>
    <li><%= link_to label.description, label_path(label) %></li>
  </ul>
  <% end %>
</p>

<p>
  <%= link_to "Edit", edit_recipe_path(@recipe) %> |
  <%= link_to "Delete", @recipe, :confirm => "Are you sure?", :method => :delete %>
</p>